// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDFJGdd0O9MS2_qGR4dB_IzwoKVDy-PXNg',
//     appId: '1:65526730176:android:cfd96768745511ef708c25',
//     messagingSenderId: '65526730176',
//     projectId: 'zcart-vendor',
//     storageBucket: 'zcart-vendor.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAbP5Nm-MJjkqvqkZ3peyZajP6tpXT51DY',
//     appId: '1:65526730176:ios:78d25b0ef46a7ae2708c25',
//     messagingSenderId: '65526730176',
//     projectId: 'zcart-vendor',
//     storageBucket: 'zcart-vendor.appspot.com',
//     iosClientId: '65526730176-t10oic2esfilv94ftl09efl7d8at70dg.apps.googleusercontent.com',
//     iosBundleId: 'com.example.multivendorStore',
//   );
// }
